FROM python:3.13-alpine

WORKDIR /redirect.luenyx.com

COPY . .

RUN pip install --no-cache-dir -r ./deploy/server-python-dependencies.txt

EXPOSE 44448

CMD ["gunicorn", "--bind", "0.0.0.0:44448", "--workers", "2", "server.main:server"]
